version: '2'
services:

  db:
    image: postgres
    container_name: persona-postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "!admin010!"
    ports:
      - "15432:5432"

  api:
    container_name: persona-api
    build: .
    ports:
      - "8181:8181"
    depends_on:
      - db

volumes:
  db-data: